export const GET_APPLICATIONS = "GET_APPLICATIONS"
export const CREATE_APPLICATION = "CREATE_APPLICATION"
export const CHANGE_CURRENT_APPLICATION = "CHANGE_CURRENT_APPLICATION"

export const TOGGLE_MENU = "TOGGLE_MENU"

export const TOGGLE_COMPANY = "TOGGLE_COMPANY"